# Auto-Generated ETL Script
# Generated by: V&V Compiler
# Dialect: Tidyverse

library(tidyverse)
library(lubridate)
library(haven)

# Op: op_001_load
source_hello.csv <- read_csv("hello.csv")

# Op: op_002_sort
ds_001_sorted <- source_hello.csv %>% arrange(id)

# Op: op_003_save
write_csv(ds_001_sorted, "hello_sorted.csv")
