# Auto-Generated ETL Script
# Generated by: V&V Compiler
# Dialect: Tidyverse

library(tidyverse)
library(lubridate)
library(haven)

# Op: op_001_load
source_input.sav <- read_sav("input.sav")

# Op: op_002_save
write_sav(source_input.sav, "output.sav")
