# Auto-Generated ETL Script
# Generated by: V&V Compiler
# Dialect: Tidyverse

library(tidyverse)
library(lubridate)
library(haven)

# Op: op_001_load
source_input_template.csv <- read_csv("input_template.csv")

# Op: op_002_exec
ds_001_materialized <- source_input_template.csv

# Op: batch_op_003_compute
ds_024_derived <- ds_001_materialized %>%
  mutate(
    VType_Binary1 = 0,
    VType_Binary1 = VType_Binary1 == if_else(VType1 == 1 | VType2 == 1 | VType3 == 1, 1, VType_Binary1),
    # alternative: case_when(...)
    VType_Binary1 = VType_Binary1 == if_else(!(VType1 == 1 | VType2 == 1 | VType3 == 1), - 8, VType_Binary1),
    # alternative: case_when(...)
    VType_Binary2 = 0,
    VType_Binary2 = VType_Binary2 == if_else(VType1 == 2 | VType2 == 2 | VType3 == 2, 1, VType_Binary2),
    # alternative: case_when(...)
    VType_Binary2 = VType_Binary2 == if_else(!(VType1 == 2 | VType2 == 2 | VType3 == 2), - 8, VType_Binary2),
    # alternative: case_when(...)
    VType_Binary3 = 0,
    VType_Binary3 = VType_Binary3 == if_else(VType1 == 3 | VType2 == 3 | VType3 == 3, 1, VType_Binary3),
    # alternative: case_when(...)
    VType_Binary3 = VType_Binary3 == if_else(!(VType1 == 3 | VType2 == 3 | VType3 == 3), - 8, VType_Binary3),
    # alternative: case_when(...)
    VoTyp_Binary1 = 0,
    VoTyp_Binary1 = VoTyp_Binary1 == if_else(VoTyp1 == 1 | VoTyp2 == 1 | VoTyp3 == 1 | VoTyp4 == 1 | VoTyp5 == 1, 1, VoTyp_Binary1),
    # alternative: case_when(...)
    VoTyp_Binary1 = VoTyp_Binary1 == if_else(!(VoTyp1 == 1 | VoTyp2 == 1 | VoTyp3 == 1 | VoTyp4 == 1 | VoTyp5 == 1), - 8, VoTyp_Binary1)
    # alternative: case_when(...)
  )

# Op: op_027_generic
# WARNING: Generic command 'VARIABLE' not fully supported yet.
# ds_026_generic <- ds_024_derived

# Op: op_028_generic
# WARNING: Generic command 'VALUE' not fully supported yet.
# ds_027_generic <- ds_026_generic

# Op: op_029_exec
ds_028_materialized <- ds_027_generic
