# Auto-Generated ETL Script
# Generated by: V&V Compiler
# Dialect: Tidyverse

library(tidyverse)
library(lubridate)
library(haven)

# Op: op_001_load
source_control_vars.csv <- read_csv("control_vars.csv")

# Op: batch_op_002_compute
ds_015_derived <- source_control_vars.csv %>%
  mutate(
    min_age_n = NA,
    max_age_n = NA,
    reference_month_n = NA,
    min_age_n = min_age_n == if_else(RTRIM(parameter) == "MIN_AGE", NUMBER(value, F3.0), min_age_n),
    # alternative: case_when(...)
    max_age_n = max_age_n == if_else(RTRIM(parameter) == "MAX_AGE", NUMBER(value, F3.0), max_age_n),
    # alternative: case_when(...)
    reference_month_n = reference_month_n == if_else(RTRIM(parameter) == "REFERENCE_MONTH", NUMBER(value, F6.0), reference_month_n),
    # alternative: case_when(...)
    exclude_status_s = exclude_status_s == if_else(RTRIM(parameter) == "EXCLUDE_STATUS", value, exclude_status_s)
    # alternative: case_when(...)
  )

# Op: op_018_exec
ds_017_materialized <- ds_015_derived

# Op: op_019_filter
ds_018_filtered <- ds_017_materialized %>% filter(NOT MISSING(min_age_n))

# Op: op_020_compute
ds_019_derived <- ds_018_filtered %>% mutate(join_key = 1)

# Op: op_021_exec
ds_020_materialized <- ds_019_derived

# Op: op_022_save
write_sav(ds_020_materialized, "control_values.sav")

# Op: op_023_load
source_benefit_rates.csv <- read_csv("benefit_rates.csv")

# Op: op_024_sort
ds_021_sorted <- source_benefit_rates.csv %>% arrange(benefit_type)

# Op: op_025_save
write_sav(ds_021_sorted, "benefit_rates.sav")

# Op: op_026_load
source_claims_data.csv <- read_csv("claims_data.csv")

# Op: op_027_compute
ds_022_derived <- source_claims_data.csv %>% mutate(join_key = 1)

# Op: op_028_exec
ds_023_materialized <- ds_022_derived

# Op: op_029_join
ds_024_joined <- ds_023_materialized %>% left_join(file_control_values.sav)

# Op: op_030_exec
ds_025_materialized <- ds_024_joined

# Op: batch_op_031_compute
ds_046_derived <- ds_025_materialized %>%
  mutate(
    dob_num = NUMBER(dob, F8.0),
    claim_start_num = NUMBER(claim_start, F8.0),
    claim_end_num = NUMBER(claim_end, F8.0),
    dob_date = make_date(year=floor(dob_num / 10000, month=floor(dob_num %% 10000 / 100), day=dob_num %% 100)),
    claim_start_date = make_date(year=floor(claim_start_num / 10000, month=floor(claim_start_num %% 10000 / 100), day=claim_start_num %% 100)),
    claim_end_date = make_date(year=floor(claim_end_num / 10000, month=floor(claim_end_num %% 10000 / 100), day=claim_end_num %% 100)),
    age_years = floor((claim_start_date - dob_date) / (365.25 * 86400)),
    age_valid = 1,
    age_valid = 0,
    age_valid = 0,
    status_valid = 1,
    status_valid = 0,
    ref_year = floor(reference_month_n / 100),
    ref_month = reference_month_n %% 100,
    month_start = make_date(year=ref_year, month=ref_month, day=1),
    month_end = make_date(year=ref_year, month=ref_month + 1, day=1) - 1,
    eligible_start = MAX(claim_start_date, month_start),
    eligible_end = MIN(claim_end_date, month_end),
    eligible_days = (eligible_end - eligible_start) / 86400 + 1,
    eligible_days = 0
  )

# Op: op_052_sort
ds_047_sorted <- ds_046_derived %>% arrange(benefit_type)

# Op: op_053_join
ds_048_joined <- ds_047_sorted %>% left_join(file_benefit_rates.sav)

# Op: op_054_exec
ds_049_materialized <- ds_048_joined

# Op: batch_op_055_compute
ds_051_derived <- ds_049_materialized %>%
  mutate(
    daily_rate = weekly_rate / 7,
    payment_amount = eligible_days * daily_rate
  )

# Op: op_057_filter
ds_052_filtered <- ds_051_derived %>% filter((age_valid == 1 & status_valid == 1 & eligible_days > 0))

# Op: op_058_aggregate
ds_053_agg_active <- ds_052_filtered %>%
  group_by(benefit_type, region) %>%
  summarise(TOTAL_PAID = SUM(payment_amount , na.rm = TRUE))

# Op: op_059_save
write_csv(ds_053_agg_active, "benefit_monthly_summary.csv")
